// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgdi4r3M5AVctYXS8xMndGCyqyr1HvHIM',
    appId: '1:457361704496:web:cc9ff35ff446adb47c8ff5',
    messagingSenderId: '457361704496',
    projectId: 'ceddit-de982',
    authDomain: 'ceddit-de982.firebaseapp.com',
    storageBucket: 'ceddit-de982.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDSd9ii3vI2Rd02zmiZCNEjn-Pdf_SdAg',
    appId: '1:457361704496:android:4d1195b96c4f6b4e7c8ff5',
    messagingSenderId: '457361704496',
    projectId: 'ceddit-de982',
    storageBucket: 'ceddit-de982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdCQmKD1kWZYGmq4Kj3uTVcN6z0M4_tjk',
    appId: '1:457361704496:ios:24bb00498aae880f7c8ff5',
    messagingSenderId: '457361704496',
    projectId: 'ceddit-de982',
    storageBucket: 'ceddit-de982.appspot.com',
    iosBundleId: 'com.example.ceddit',
  );
}
